version: "3"
services: 
    apache-php7:
        build: ./php
        container_name: "webservice"
        volumes:
            - ../html:/var/www/html
        ports:
            - 80:80
            - 443:443
        networks: 
            - mynetwork
        restart: always
networks: 
    mynetwork:
        driver: bridge